export const ACTIVATE_EMAIL_FAIL = 'ACTIVATE_EMAIL_FAIL';
export const ACTIVATE_EMAIL_RESET = 'ACTIVATE_EMAIL_RESET';
export const ACTIVATE_EMAIL_START = 'ACTIVATE_EMAIL_START';
export const ACTIVATE_EMAIL_SUCCESS = 'ACTIVATE_EMAIL_SUCCESS';