export const ADD_ITEM_FAIL = 'ADD_ITEM_FAIL';
export const ADD_ITEM_REQUEST = 'ADD_ITEM_REQUEST';
export const ADD_ITEM_SUCCESS = 'ADD_ITEM_SUCCESS';

export const EDIT_ITEM_FAIL = 'EDIT_ITEM_FAIL';
export const EDIT_ITEM_REQUEST = 'EDIT_ITEM_REQUEST';
export const EDIT_ITEM_SUCCESS = 'EDIT_ITEM_SUCCESS';

export const DELETE_ITEM_FAIL = 'DELETE_ITEM_FAIL';
export const DELETE_ITEM_REQUEST = 'DELETE_ITEM_REQUEST';
export const DELETE_ITEM_SUCCESS = 'DELETE_ITEM_SUCCESS';

export const FETCH_BUDGET_FAIL = 'FETCH_BUDGET_FAIL';
export const FETCH_BUDGET_RESET = 'FETCH_BUDGET_RESET';
export const FETCH_BUDGET_REQUEST = 'FETCH_BUDGET_REQUEST';
export const FETCH_BUDGET_SUCCESS = 'FETCH_BUDGET_SUCCESS';

export const FETCH_FEATURES_FAIL = 'FETCH_FEATURES_FAIL';
export const FETCH_FEATURES_REQUEST = 'FETCH_FEATURES_REQUEST';
export const FETCH_FEATURES_SUCCESS = 'FETCH_FEATURES_SUCCESS';