export const FETCH_BUDGET_FAIL = 'FETCH_BUDGET_FAIL';
export const FETCH_BUDGET_RESET = 'FETCH_BUDGET_RESET';
export const FETCH_BUDGET_REQUEST = 'FETCH_BUDGET_REQUEST';
export const FETCH_BUDGET_SUCCESS = 'FETCH_BUDGET_SUCCESS';

export const FETCH_FEATURES_FAIL = 'FETCH_FEATURES_FAIL';
export const FETCH_FEATURES_REQUEST = 'FETCH_FEATURES_REQUEST';
export const FETCH_FEATURES_SUCCESS = 'FETCH_FEATURES_SUCCESS';