export const BUDGET_ERROR = 'BUDGET_ERROR';
export const BUDGET_RESET = 'BUDGET_RESET';
export const BUDGET_LAUNCH = 'BUDGET_LAUNCH';
export const SUCCESSFUL_BUDGET = 'SUCCESSFUL_BUDGET';

export const ADD_ITEM_ERROR = 'ADD_ITEM_ERROR';
export const ADD_ITEM_LAUNCH = 'ADD_ITEM_LAUNCH';
export const SUCCESSFUL_ADD_ITEM = 'SUCCESSFUL_ADD_ITEM';

export const EDIT_ITEM_ERROR = 'EDIT_ITEM_ERROR';
export const EDIT_ITEM_LAUNCH = 'EDIT_ITEM_LAUNCH';
export const SUCCESSFUL_EDIT_ITEM = 'SUCCESSFUL_EDIT_ITEM';

export const DELETE_ITEM_ERROR = 'DELETE_ITEM_ERROR';
export const DELETE_ITEM_LAUNCH = 'DELETE_ITEM_LAUNCH';
export const SUCCESSFUL_DELETE_ITEM = 'SUCCESSFUL_DELETE_ITEM';
