export const FEATURES_ERROR = 'FEATURES_ERROR';
export const FEATURES_RESET = 'FEATURES_RESET';
export const FEATURES_LAUNCH = 'FEATURES_LAUNCH';
export const SUCCESSFUL_FEATURES = 'SUCCESSFUL_FEATURES';