export const PASSWORD_RECOVERY_ERROR = 'PASSWORD_RECOVERY_ERROR';
export const PASSWORD_RECOVERY_RESET = 'PASSWORD_RECOVERY_RESET';
export const PASSWORD_RECOVERY_LOUNCH = 'PASSWORD_RECOVERY_LOUNCH';
export const SUCCESSFUL_PASSWORD_RECOVERY = 'SUCCESSFUL_PASSWORD_RECOVERY';