export const STATISTICS_ERROR = 'STATISTICS_ERROR';
export const STATISTICS_RESET = 'STATISTICS_RESET';
export const STATISTICS_LAUNCH = 'STATISTICS_LAUNCH';
export const SUCCESSFUL_STATISTICS = 'SUCCESSFUL_STATISTICS';