export const SETTINGS_ERROR = 'SETTINGS_ERROR';
export const SETTINGS_RESET = 'SETTINGS_RESET';
export const SETTINGS_LAUNCH = 'SETTINGS_LAUNCH';
export const SUCCESSFUL_SETTINGS = 'SUCCESSFUL_SETTINGS';

export const CHANGE_EMAIL_ERROR = 'CHANGE_EMAIL_ERROR';
export const CHANGE_EMAIL_LAUNCH = 'CHANGE_EMAIL_LAUNCH';
export const SUCCESSFUL_CHANGE_EMAIL = 'SUCCESSFUL_CHANGE_EMAIL';

export const DELETE_ACCOUNT_ERROR = 'DELETE_ACCOUNT_ERROR';
export const DELETE_ACCOUNT_LAUNCH = 'DELETE_ACCOUNT_LAUNCH';
export const SUCCESSFUL_DELETE_ACCOUNT = 'SUCCESSFUL_DELETE_ACCOUNT';

export const CHANGE_PASSWORD_ERROR = 'CHANGE_PASSWORD_ERROR';
export const CHANGE_PASSWORD_LAUNCH = 'CHANGE_PASSWORD_LAUNCH';
export const SUCCESSFUL_CHANGE_PASSWORD = 'SUCCESSFUL_CHANGE_PASSWORD';