export const PASSWORD_RESET_ERROR = 'PASSWORD_RESET_ERROR';
export const RESET_PASSWORD_RESET = 'RESET_PASSWORD_RESET';
export const PASSWORD_RESET_LAUNCH = 'PASSWORD_RESET_LAUNCH';
export const SUCCESSFUL_PASSWORD_RESET = 'SUCCESSFUL_PASSWORD_RESET';