export const CONTACT_ERROR = 'CONTACT_ERROR';
export const CONTACT_RESET = 'CONTACT_RESET';
export const CONTACT_LAUNCH = 'CONTACT_LAUNCH';
export const SUCCESSFUL_CONTACT = 'SUCCESSFUL_CONTACT';

export const SENDING_ERROR_MESSAGE = 'SENDING_ERROR_MESSAGE';
export const SENDING_MESSAGE_LAUNCH = 'SENDING_MESSAGE_LAUNCH';
export const SUCCESSFUL_SENDING_MESSAGE = 'SUCCESSFUL_SENDING_MESSAGE';
