export const ACTIVATE_EMAIL_RESET = 'ACTIVATE_EMAIL_RESET';
export const ACTIVATE_EMAIL_LAUNCH = 'ACTIVATE_EMAIL_LAUNCH';
export const EMAIL_ACTIVATION_ERROR = 'EMAIL_ACTIVATION_ERROR';
export const SUCCESSFUL_EMAIL_ACTIVATION = 'SUCCESSFUL_EMAIL_ACTIVATION';