export const VERIFY_EMAIL_ERROR = 'VERIFY_EMAIL_ERROR';
export const RESET_VERIFY_EMAIL = 'RESET_VERIFY_EMAIL';
export const LOUNCH_VERIFY_EMAIL = 'LOUNCH_VERIFY_EMAIL';
export const REQUEST_VERIFY_EMAIL = 'REQUEST_VERIFY_EMAIL';
export const SUCCESSFUL_VERIFY_EMAIL = 'SUCCESSFUL_VERIFY_EMAIL';
export const EMAIL_VERIFICATION_CONNECTION = 'EMAIL_VERIFICATION_CONNECTION';