export const FETCH_FEATURES_FAIL = 'FETCH_FEATURES_FAIL';
export const FETCH_FEATURES_RESET = 'FETCH_FEATURES_RESET';
export const FETCH_FEATURES_REQUEST = 'FETCH_FEATURES_REQUEST';
export const FETCH_FEATURES_SUCCESS = 'FETCH_FEATURES_SUCCESS';