export const RECOVER_PASSWORD_FAIL = 'RECOVER_PASSWORD_FAIL';
export const RECOVER_PASSWORD_RESET = 'RECOVER_PASSWORD_RESET';
export const RECOVER_PASSWORD_START = 'RECOVER_PASSWORD_START';
export const RECOVER_PASSWORD_SUCCESS = 'RECOVER_PASSWORD_SUCCESS';