export const FETCH_STATISTIC_FAIL = 'FETCH_STATISTIC_FAIL';
export const FETCH_STATISTIC_RESET = 'FETCH_STATISTIC_RESET';
export const FETCH_STATISTIC_REQUEST = 'FETCH_STATISTIC_REQUEST';
export const FETCH_STATISTIC_SUCCESS = 'FETCH_STATISTIC_SUCCESS';